import type { ReactNode } from "react";

import type { Metadata } from "next";

import GlobalFooter from "@/components/layout/GlobalFooter";
import GlobalNav from "@/components/layout/GlobalNav";
import AppProvider from "@/providers";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProvider>
          <GlobalNav />
          <main
            className="h-screen flex-1 border border-violet-500 overflow-y-auto"
            style={{ height: "calc(100vh - 70px - 60px)" }}
          >
            {children}
          </main>
          <GlobalFooter />
        </AppProvider>
      </body>
    </html>
  );
}
